### ISSUE TITLE
Double scrollbars showing on Windows.

### ISSUE THREAD

**Issue by jachui** [cdes/figma-material-design-icons-plugin#1]
![image](https://user-images.githubusercontent.com/29107631/53440910-8041b180-39ba-11e9-81f2-3063d5b1a950.png)

Two scrollbars are showing on Windows. I think it's caused by .scrollable having overflow-y: scroll;
This can be fixed by setting it to overflow-y: auto

**Comment by cdes** [comment]
Fixed in https://github.com/cdes/figma-material-design-icons-plugin/commit/330892154d42fc7d2f66c26014bad74546f813e2
