### ISSUE TITLE
Can't see plugin in Figma+ menu

### ISSUE THREAD

**Issue by olesay** [cdes/figma-material-design-icons-plugin#2]
Can't find it in App, on mac PO v.10.14.4 (18E226)
Plugin was installed.
<img width="618" alt="Снимок экрана 2019-05-08 в 15 12 14" src="https://user-images.githubusercontent.com/40247234/57374584-e3fb0e80-71a3-11e9-806e-ea3aa80b67da.png">

**Comment by cdes** [comment]
@olesay This plugin does not add a selection command. Use the hamburger menu or the shortcut (Command+Shift+M)
![image](https://user-images.githubusercontent.com/1207863/57439108-faf63b00-724d-11e9-8e0f-5c3b47fe2b11.png)
